[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/iban_issue_token"
  to = "/.netlify/functions/iban_issue_token"
  status = 200

[[redirects]]
  from = "/api/iban_submit"
  to = "/.netlify/functions/iban_submit"
  status = 200
  
  [[redirects]]
  from = "/api/send_iban_email"
  to = "/.netlify/functions/send_iban_email"
  status = 200

