[build]
  publish = "."
  functions = "netlify/functions"

# --- API Redirects (unverändert) ---
[[redirects]]
  from = "/api/iban_issue_token"
  to = "/.netlify/functions/iban_issue_token"
  status = 200

[[redirects]]
  from = "/api/iban_submit"
  to = "/.netlify/functions/iban_submit"
  status = 200

[[redirects]]
  from = "/api/send_iban_email"
  to = "/.netlify/functions/send_iban_email"
  status = 200

# --- Security Hardening (risikoarm, kompatibel) ---

# 1) Globale Sicherheits-Header
[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options    = "nosniff"
    X-Frame-Options           = "DENY"
    Referrer-Policy           = "strict-origin-when-cross-origin"
    Permissions-Policy        = "camera=(), microphone=(), geolocation=()"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    # CSP mit 'unsafe-inline' damit dein aktuelles Frontend nicht bricht
    Content-Security-Policy   = "default-src 'self'; connect-src 'self'; img-src 'self' data:; font-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'; form-action 'self'"

# 2) Kein Caching für Seiten im Verify-Flow
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/verify.html"
  [headers.values]
    Cache-Control = "no-store"

[[headers]]
  for = "/danke.html"
  [headers.values]
    Cache-Control = "no-store"
